version: '3.7'

services:
  postgres:
    image: kartoza/postgis:11.5-2.5
    container_name: postgres-junehome
    restart: always
    environment:
      - POSTGRES_USER=junehome
      - POSTGRES_PASSWORD=pass111
      - POSTGRES_DB=junehomedb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  junehome:
    build:
      context: ./
      dockerfile: Dockerfile
    image: junehome
    container_name: junehome
    command: /usr/local/bin/gunicorn junehome.wsgi -w 1 -b 0.0.0.0:8000 -t 0 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
       - ./app:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
